### ISSUE TITLE
Upload to a Maven repository

### ISSUE THREAD

**Issue by skuro** [otabat/shen-jvm#1]
Would be much easier to enjoy `shen-jvm` if it was deployed in any Maven-accessible repository. [Sonatype OSS](http://central.sonatype.org/pages/ossrh-guide.html) could be a good place to start.

**Comment by otabat** [comment]
Good suggestion. I'm currently busy developing the Android version of Shen-JVM, but after that probably in a few days I would like to come back on this issue and consider a Maven repo including your suggested one.

**Comment by otabat** [comment]
I have chosen JCenter and uploaded the Shen-JVM version 0.2.3.
https://github.com/otabat/shen-jvm#download-from-jcenter
