### ISSUE TITLE
Graal

### ISSUE THREAD

**Issue by JacobGood1** [otabat/shen-jvm#2]
Hello, this is great work! Have you thought about trying to use Graal(Truffle) to implement Shen?

**Comment by otabat** [comment]
Hi, thanks for the interest!
Since I have Android support in my mind, I have not thought about an implementation in Graal (Truffle) so far. But they are really interesting technologies including the Substrate VM and I may change my mind in the future :)

**Comment by JacobGood1** [comment]
Sounds good!
