### ISSUE TITLE
check-sysfunc-in-name

### ISSUE THREAD

**Issue by tizoc** [otabat/shen-jvm#3]
Hello @otabat, I'm about to publish a new release of the Shen kernel sources, which solves your need for having to override the "declarations" and "types" file.

What is missing is your override of "core". Can you tell me a bit more about why you need this? That will help me figure out a way for you to not have to do this anymore.

**Comment by tizoc** [comment]
This is what I'm talking about btw: https://github.com/Shen-Language/shen-sources/blob/master/doc/port-upgrades.md#dynamic-code-expansion

**Comment by otabat** [comment]
Hi, thanks for your efforts! As far as I remember, there was an issue when executing make.shen and adding *check-sysfunc-in-name* was a temporary hack to bypass that.

**Comment by tizoc** [comment]
Ok, I will make a new release in the next following days, when you upgrade your ports if you hit any problem related to this let me know and I will see what I can do.

**Comment by otabat** [comment]
Thanks!
